"""Add Accession Job

Revision ID: 2023_11_29_04_56_53
Revises: 2023_11_27_11:26:47
Create Date: 2023-11-29 03:56:53.241421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_11_29_04_56_53'
down_revision: Union[str, None] = '2023_11_27_11_26_47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accession_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trayed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('Created', 'Paused', 'Running', 'Cancelled', 'Completed', 'Verified', name='accession_status'), nullable=True),
    sa.Column('user_id', sa.SmallInteger(), nullable=True),
    sa.Column('run_time', sa.Interval(), nullable=True),
    sa.Column('last_transition', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('container_type_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['container_type_id'], ['container_types.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accession_jobs')
    # ### end Alembic commands ###
