"""Add ladders

Revision ID: 2023_11_05_12_14_47
Revises: 2023_10_18_07:44:56
Create Date: 2023-11-05 11:14:47.051830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_11_05_12_14_47'
down_revision: Union[str, None] = '2023_10_19_11_37_46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ladder_numbers',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('ladders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ladder_number_id', sa.Integer(), nullable=False),
    sa.Column('side_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ladder_number_id'], ['ladder_numbers.id'], ),
    sa.ForeignKeyConstraint(['side_id'], ['sides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ladders')
    op.drop_table('ladder_numbers')
    # ### end Alembic commands ###
