"""Add shelves

Revision ID: 2023_11_24_12_19_22
Revises: 2023_11_16_11:18:56
Create Date: 2023-11-24 11:19:22.962514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_11_24_12_19_22'
down_revision: Union[str, None] = '2023_11_16_11_18_56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('shelf_numbers',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('shelf_position_numbers',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('capacity', sa.SmallInteger(), nullable=False),
    sa.Column('height', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('width', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('depth', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('container_type_id', sa.Integer(), nullable=False),
    sa.Column('shelf_number_id', sa.Integer(), nullable=False),
    sa.Column('ladder_id', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['barcode_id'], ['barcodes.id'], ),
    sa.ForeignKeyConstraint(['container_type_id'], ['container_types.id'], ),
    sa.ForeignKeyConstraint(['ladder_id'], ['ladders.id'], ),
    sa.ForeignKeyConstraint(['shelf_number_id'], ['shelf_numbers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode_id'),
    sa.UniqueConstraint('ladder_id', 'shelf_number_id', name='uq_ladder_id_shelf_number_id')
    )
    op.create_table('shelf_positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shelf_position_number_id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ),
    sa.ForeignKeyConstraint(['shelf_position_number_id'], ['shelf_position_numbers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shelf_id', 'shelf_position_number_id', name='uq_shelf_id_shelf_position_number_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelf_positions')
    op.drop_table('shelves')
    op.drop_table('shelf_position_numbers')
    op.drop_table('shelf_numbers')
    op.drop_table('container_types')
    # ### end Alembic commands ###
