"""aisle unique together update

Revision ID: 2023_10_18_07_44_56
Revises: 2023_10_18_06:29:39
Create Date: 2023-10-18 06:44:56.959877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_10_18_07_44_56'
down_revision: Union[str, None] = '2023_10_18_06_29_39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_building_module_aisle_number_id', 'aisles', type_='unique')
    op.create_unique_constraint('uq_building_aisle_number_id', 'aisles', ['building_id', 'aisle_number_id'])
    op.create_unique_constraint('uq_module_aisle_number_id', 'aisles', ['module_id', 'aisle_number_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_module_aisle_number_id', 'aisles', type_='unique')
    op.drop_constraint('uq_building_aisle_number_id', 'aisles', type_='unique')
    op.create_unique_constraint('uq_building_module_aisle_number_id', 'aisles', ['building_id', 'module_id', 'aisle_number_id'])
    # ### end Alembic commands ###
