"""Update ladder barcode id foregin key

Revision ID: 7813b0d58cc0
Revises: 2023_11_05_16:26:32
Create Date: 2023-11-07 11:25:48.253547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = "2023_11_07_11_25_48"
down_revision: Union[str, None] = "2023_11_05_16_26_32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ladders", sa.Column("barcode_id", sa.dialects.postgresql.UUID(), nullable=True)
    )
    op.create_foreign_key(None, "ladders", "barcodes", ["barcode_id"], ["id"])
    op.drop_column("ladders", "barcode")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ladders", sa.Column("barcode", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "ladders", type_="foreignkey")
    op.drop_column("ladders", "barcode_id")
    # ### end Alembic commands ###
