"""set unique_together side aisle_orientation

Revision ID: 2023_11_05_14_57_19
Revises: 2023_11_05_12:14:47
Create Date: 2023-11-05 13:57:19.908770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_11_05_14_57_19'
down_revision: Union[str, None] = '2023_11_05_12_14_47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_aisle_id_side_orientation_id', 'sides', ['aisle_id', 'side_orientation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_aisle_id_side_orientation_id', 'sides', type_='unique')
    # ### end Alembic commands ###
