"""Owner Parent Owner

Revision ID: 2023_12_27_12_13_12
Revises: 2023_11_29_04:56:53
Create Date: 2023-12-27 11:13:12.600153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_12_27_12_13_12'
down_revision: Union[str, None] = '2023_11_29_04_56_53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('parent_owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_owners_parent_owner_id", 'owners', 'owners', ['parent_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_owners_parent_owner_id", 'owners', type_='foreignkey')
    op.drop_column('owners', 'parent_owner_id')
    # ### end Alembic commands ###
