"""Add Module table

Revision ID: 2023_10_15_06_54_53
Revises: 2023_10_15_06:52:16
Create Date: 2023-10-15 05:54:53.768188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_10_15_06_54_53'
down_revision: Union[str, None] = '2023_10_15_06_52_16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('module_number_id', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['module_number_id'], ['module_numbers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'module_number_id', name='uq_building_id_module_number_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modules')
    # ### end Alembic commands ###
