"""Added scan for refile

Revision ID: 2024_06_12_19_26_05
Revises: 2024_06_11_13:53:01
Create Date: 2024-06-12 23:26:05.730882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2024_06_12_19_26_05"
down_revision: Union[str, None] = "2024_06_11_13_53_01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("scanned_for_refile_queue", sa.Boolean(), nullable=False, server_default="False")
    )
    op.add_column(
        "items", sa.Column("scanned_for_refile", sa.Boolean(), nullable=False, server_default="False")
    )
    op.add_column(
        "non_tray_items",
        sa.Column("scanned_for_refile_queue", sa.Boolean(), nullable=False, server_default="False"),
    )
    op.add_column(
        "non_tray_items", sa.Column("scanned_for_refile", sa.Boolean(), nullable=False, server_default="False")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("non_tray_items", "scanned_for_refile")
    op.drop_column("non_tray_items", "scanned_for_refile_queue")
    op.drop_column("items", "scanned_for_refile")
    op.drop_column("items", "scanned_for_refile_queue")
    # ### end Alembic commands ###
