"""accession_job_media_type

Revision ID: 2024_03_15_16_32_03
Revises: 2024_03_15_15:22:10
Create Date: 2024-03-15 15:32:03.578537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_03_15_16_32_03'
down_revision: Union[str, None] = '2024_03_15_15_22_10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accession_jobs', sa.Column('media_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key("accession_job_media_type_fk", 'accession_jobs', 'media_types', ['media_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("accession_job_media_type_fk", 'accession_jobs', type_='foreignkey')
    op.drop_column('accession_jobs', 'media_type_id')
    # ### end Alembic commands ###
