"""Add Shelving Job and Association tables

Revision ID: 2024_02_01_13_37_50
Revises: 2024_01_25_09:09:29
Create Date: 2024-02-01 18:37:50.794550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = "2024_02_01_13_37_50"
down_revision: Union[str, None] = "2024_01_25_09_09_29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shelving_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "Created",
                "Paused",
                "Running",
                "Cancelled",
                "Completed",
                name="shelving_status",
            ),
            nullable=True,
        ),
        sa.Column("user_id", sa.SmallInteger(), nullable=True),
        sa.Column("run_time", sa.Interval(), nullable=True),
        sa.Column("last_transition", sa.DateTime(), nullable=True),
        sa.Column("create_dt", sa.DateTime(), nullable=False),
        sa.Column("update_dt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shelving_job_tray_associations",
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("shelf_position_proposed_id", sa.Integer(), nullable=False),
        sa.Column("shelf_position_id", sa.Integer(), nullable=False),
        sa.Column("shelving_job_id", sa.Integer(), nullable=False),
        sa.Column("tray_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shelf_position_id"],
            ["shelf_positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shelf_position_proposed_id"],
            ["shelf_positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shelving_job_id"],
            ["shelving_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tray_id"],
            ["trays.id"],
        ),
        sa.PrimaryKeyConstraint("shelving_job_id", "tray_id"),
    )
    op.create_table(
        "shelving_job_item_associations",
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("shelf_position_proposed_id", sa.Integer(), nullable=False),
        sa.Column("shelf_position_id", sa.Integer(), nullable=False),
        sa.Column("shelving_job_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shelf_position_id"],
            ["shelf_positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shelf_position_proposed_id"],
            ["shelf_positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shelving_job_id"],
            ["shelving_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("shelving_job_id", "item_id"),
    )
    op.add_column(
        "verification_jobs", sa.Column("shelving_job_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_verification_shelving_jobs", "verification_jobs", "shelving_jobs", ["shelving_job_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_verification_shelving_jobs", "verification_jobs", type_="foreignkey")
    op.drop_column("verification_jobs", "shelving_job_id")
    op.drop_table("shelving_job_item_associations")
    op.drop_table("shelving_job_tray_associations")
    op.drop_table("shelving_jobs")
    # ### end Alembic commands ###
