"""acc_ver_run_time

Revision ID: 2024_05_21_12_12_55
Revises: 2024_05_16_12:49:11
Create Date: 2024-05-21 11:12:55.024452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2024_05_21_12_12_55'
down_revision: Union[str, None] = '2024_05_16_12_49_11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE accession_jobs SET run_time = '0 days' WHERE run_time IS NULL")
    op.execute("UPDATE verification_jobs SET run_time = '0 days' WHERE run_time IS NULL")
    op.alter_column('accession_jobs', 'run_time',
               existing_type=postgresql.INTERVAL(),
               nullable=False, server_default=sa.text("'0 days'"))
    op.alter_column('verification_jobs', 'run_time',
               existing_type=postgresql.INTERVAL(),
               nullable=False, server_default=sa.text("'0 days'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_jobs', 'run_time',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    op.alter_column('accession_jobs', 'run_time',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    # ### end Alembic commands ###
