"""Adding Pick List Status

Revision ID: 2024_12_19_16_50_19
Revises: 2024_12_16_20:53:02
Create Date: 2024-12-19 21:50:19.881809

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa
from app.models.items import ItemStatus
from app.models.non_tray_items import NonTrayItemStatus



# revision identifiers, used by Alembic.
revision: str = '2024_12_19_16_50_19'
down_revision: Union[str, None] = '2024_12_16_20_53_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Extend existing ENUM for `items.status`
    op.execute("ALTER TYPE item_status ADD VALUE 'PickList'")

    # Extend  existing ENUM for `non_tray_items.status`
    op.execute("ALTER TYPE non_tray_item_status ADD VALUE 'PickList'")




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrade is trickier for ENUMs in PostgreSQL as values cannot be removed.
    # Recreate the ENUM without the value 'Pick List' for `items.status`.
    op.execute(
        """
        CREATE TYPE item_status_tmp AS ENUM (
            'In', 'Out', 'Requested', 'Withdrawn'
        );
        """
    )
    op.execute(
        "ALTER TABLE items ALTER COLUMN status TYPE item_status_tmp USING status::text::item_status_tmp"
        )
    op.execute("DROP TYPE non_tray_item_status")
    op.execute("ALTER TYPE non_tray_item_status_tmp RENAME TO non_tray_item_status")
    # Recreate the ENUM without the value 'Pick List' for `non_tray_items.status`.
    op.execute(
        """
        CREATE TYPE non_tray_item_status_tmp AS ENUM (
            'In', 'Out', 'Requested', 'Withdrawn'
        );
        """
    )
    op.execute(
        "ALTER TABLE items ALTER COLUMN status TYPE non_tray_item_status_tmp USING status::text::non_tray_item_status_tmp"
    )
    op.execute("DROP TYPE non_tray_item_status")
    op.execute("ALTER TYPE non_tray_item_status_tmp RENAME TO non_tray_item_status")
    # ### end Alembic commands ###
#
