"""trays

Revision ID: 2024_01_10_07_33_41
Revises: 2023_12_28_20:37:30
Create Date: 2024-01-10 06:33:41.687686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_01_10_07_33_41'
down_revision: Union[str, None] = '2023_12_28_20_37_30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_job_id', sa.Integer(), nullable=True),
    sa.Column('verification_job_id', sa.Integer(), nullable=True),
    sa.Column('container_type_id', sa.Integer(), nullable=True),
    sa.Column('barcode_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('shelf_position_id', sa.Integer(), nullable=True),
    sa.Column('accession_dt', sa.DateTime(), nullable=True),
    sa.Column('shelved_dt', sa.DateTime(), nullable=True),
    sa.Column('withdrawal_dt', sa.DateTime(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accession_job_id'], ['accession_jobs.id'], ),
    sa.ForeignKeyConstraint(['barcode_id'], ['barcodes.id'], ),
    sa.ForeignKeyConstraint(['container_type_id'], ['container_types.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['shelf_position_id'], ['shelf_positions.id'], ),
    sa.ForeignKeyConstraint(['verification_job_id'], ['verification_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trays')
    # ### end Alembic commands ###
