"""Adjust ShelvingJobAssociation Subcollections

Revision ID: 2024_02_06_12_41_18
Revises: 2024_02_01_13:37:50
Create Date: 2024-02-06 17:41:18.987931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_02_06_12_41_18'
down_revision: Union[str, None] = '2024_02_01_13_37_50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelving_job_item_associations', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('shelving_job_tray_associations', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('subcollections', sa.Column('create_dt', sa.DateTime(), nullable=False))
    op.add_column('subcollections', sa.Column('update_dt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcollections', 'update_dt')
    op.drop_column('subcollections', 'create_dt')
    op.drop_column('shelving_job_tray_associations', 'id')
    op.drop_column('shelving_job_item_associations', 'id')
    # ### end Alembic commands ###
