"""barcode_allowed_pattern

Revision ID: 2024_05_16_12_49_11
Revises: 2024_05_14_10:09:52
Create Date: 2024-05-16 11:49:11.696016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_05_16_12_49_11'
down_revision: Union[str, None] = '2024_05_14_10_09_52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barcode_types', sa.Column('allowed_pattern', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barcode_types', 'allowed_pattern')
    # ### end Alembic commands ###
