"""add_user_table

Revision ID: 2024_03_31_00_30_10
Revises: 2024_03_29_12:24:09
Create Date: 2024-03-30 23:30:10.651917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_03_31_00_30_10'
down_revision: Union[str, None] = '2024_03_29_12_24_09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('accession_jobs', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key('fk_accession_job_users_id', 'accession_jobs', 'users', ['user_id'], ['id'])
    op.alter_column('shelving_jobs', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key('fk_shelving_job_users_id', 'shelving_jobs', 'users', ['user_id'], ['id'])
    op.alter_column('verification_jobs', 'user_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key('fk_verification_job_users_id', 'verification_jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_verification_job_users_id', 'verification_jobs', type_='foreignkey')
    op.alter_column('verification_jobs', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.drop_constraint('fk_shelving_job_users_id', 'shelving_jobs', type_='foreignkey')
    op.alter_column('shelving_jobs', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.drop_constraint('fk_accession_job_users_id', 'accession_jobs', type_='foreignkey')
    op.alter_column('accession_jobs', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.drop_table('users')
    # ### end Alembic commands ###
