"""tray_collection_accessioned

Revision ID: 2024_03_15_15_16_21
Revises: 2024_03_15_15:11:16
Create Date: 2024-03-15 14:16:21.741700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_03_15_15_16_21'
down_revision: Union[str, None] = '2024_03_15_15_11_16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trays', sa.Column('collection_accessioned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trays', 'collection_accessioned')
    # ### end Alembic commands ###
