"""created_by_jobs

Revision ID: 2024_11_23_19_52_08
Revises: 2024_11_03_20:14:57
Create Date: 2024-11-23 19:52:08.444643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_11_23_19_52_08'
down_revision: Union[str, None] = '2024_11_03_20_14_57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accession_jobs', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_accession_created_by_user", 'accession_jobs', 'users', ['created_by_id'], ['id'])
    op.add_column('pick_lists', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_pl_created_by_user", 'pick_lists', 'users', ['created_by_id'], ['id'])
    op.add_column('refile_jobs', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_refile_created_by_user", 'refile_jobs', 'users', ['created_by_id'], ['id'])
    op.add_column('shelving_jobs', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_shelving_created_by_user", 'shelving_jobs', 'users', ['created_by_id'], ['id'])
    op.add_column('verification_jobs', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_verification_created_by_user", 'verification_jobs', 'users', ['created_by_id'], ['id'])
    op.add_column('withdraw_jobs', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_withdraw_created_by_user", 'withdraw_jobs', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_withdraw_created_by_user", 'withdraw_jobs', type_='foreignkey')
    op.drop_column('withdraw_jobs', 'created_by_id')
    op.drop_constraint("fk_verification_created_by_user", 'verification_jobs', type_='foreignkey')
    op.drop_column('verification_jobs', 'created_by_id')
    op.drop_constraint("fk_shelving_created_by_user", 'shelving_jobs', type_='foreignkey')
    op.drop_column('shelving_jobs', 'created_by_id')
    op.drop_constraint("fk_refile_created_by_user", 'refile_jobs', type_='foreignkey')
    op.drop_column('refile_jobs', 'created_by_id')
    op.drop_constraint("fk_pl_created_by_user", 'pick_lists', type_='foreignkey')
    op.drop_column('pick_lists', 'created_by_id')
    op.drop_constraint("fk_accession_created_by_user", 'accession_jobs', type_='foreignkey')
    op.drop_column('accession_jobs', 'created_by_id')
    # ### end Alembic commands ###
