"""sizeclass

Revision ID: 2024_01_10_08_09_01
Revises: 2024_01_10_07:53:48
Create Date: 2024-01-10 07:09:01.322341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_01_10_08_09_01'
down_revision: Union[str, None] = '2024_01_10_07_53_48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tray_size_class',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('shelves', sa.Column('tray_size_class_id', sa.Integer(), nullable=False))
    op.create_foreign_key('shelves_size_class_fk', 'shelves', 'tray_size_class', ['tray_size_class_id'], ['id'])
    op.add_column('trays', sa.Column('tray_size_class_id', sa.Integer(), nullable=False))
    op.create_foreign_key('trays_size_class_fk', 'trays', 'tray_size_class', ['tray_size_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trays_size_class_fk', 'trays', type_='foreignkey')
    op.drop_column('trays', 'tray_size_class_id')
    op.drop_constraint('shelves_size_class_fk', 'shelves', type_='foreignkey')
    op.drop_column('shelves', 'tray_size_class_id')
    op.drop_table('tray_size_class')
    # ### end Alembic commands ###
