"""Added onwers size class link table

Revision ID: 2024_11_03_20_14_57
Revises: 2024_11_01_21:14:45
Create Date: 2024-11-04 01:14:57.281274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = "2024_11_03_20_14_57"
down_revision: Union[str, None] = "2024_11_01_21_14_45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "owners_size_classes",
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("size_class_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owners.id"],
        ),
        sa.ForeignKeyConstraint(
            ["size_class_id"],
            ["size_class.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id", "size_class_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("owners_size_classes")
    # ### end Alembic commands ###
