"""barcode_fk_unique_ref_models

Revision ID: 2024_03_22_09_28_10
Revises: 2024_03_21_16:31:23
Create Date: 2024-03-22 08:28:10.880906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_03_22_09_28_10'
down_revision: Union[str, None] = '2024_03_21_16_31_23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_conveyance_barcode", 'conveyance_bins', ['barcode_id'])
    op.create_unique_constraint("uq_item_barcode", 'items', ['barcode_id'])
    op.create_unique_constraint("uq_nontray_barcode", 'non_tray_items', ['barcode_id'])
    op.create_unique_constraint("uq_tray_barcode", 'trays', ['barcode_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_tray_barcode", 'trays', type_='unique')
    op.drop_constraint("uq_nontray_barcode", 'non_tray_items', type_='unique')
    op.drop_constraint("uq_item_barcode", 'items', type_='unique')
    op.drop_constraint("uq_conveyance_barcode", 'conveyance_bins', type_='unique')
    # ### end Alembic commands ###
