"""shelving_origin

Revision ID: 2024_04_23_10_49_16
Revises: 2024_04_22_16:35:56
Create Date: 2024-04-23 09:49:16.924342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision: str = '2024_04_23_10_49_16'
down_revision: Union[str, None] = '2024_04_22_16_35_56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    shelving_origin_enum = postgresql.ENUM('Verification', 'Direct', name='shelving_origin')
    shelving_origin_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('shelving_jobs', sa.Column('origin', shelving_origin_enum, nullable=True, server_default="Verification"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelving_jobs', 'origin')
    # ### end Alembic commands ###
