"""mediatype

Revision ID: 2024_01_10_07_53_48
Revises: 2024_01_10_07:33:41
Create Date: 2024-01-10 06:53:48.670079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_01_10_07_53_48'
down_revision: Union[str, None] = '2024_01_10_07_33_41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_types',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('trays', sa.Column('media_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trays', 'media_types', ['media_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trays', type_='foreignkey')
    op.drop_column('trays', 'media_type_id')
    op.drop_table('media_types')
    # ### end Alembic commands ###
