"""Added Shelf Type table

Revision ID: 2024_11_01_21_14_45
Revises: 2024_10_24_16:04:48
Create Date: 2024-11-02 01:14:45.571938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "2024_11_01_21_14_45"
down_revision: Union[str, None] = "2024_10_24_16_04_48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shelf_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("size_class_id", sa.Integer(), nullable=False),
        sa.Column("max_capacity", sa.SmallInteger(), nullable=False),
        sa.Column(
            "create_dt",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "update_dt",
            sa.DateTime(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["size_class_id"],
            ["size_class.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("shelves", sa.Column("shelf_type_id", sa.Integer(), nullable=False))
    op.drop_constraint("shelves_size_class_id_fkey", "shelves", type_="foreignkey")
    op.create_foreign_key(
        "shelf_types_id_fkey", "shelves", "shelf_types", ["shelf_type_id"], ["id"]
    )
    op.drop_column("shelves", "size_class_id")
    op.drop_column("shelves", "capacity")
    op.add_column(
        "size_class",
        sa.Column("assigned", sa.Boolean(), nullable=False, server_default="False"),
    )
    op.add_column(
        "size_class",
        sa.Column("height", sa.Numeric(precision=4, scale=2), nullable=False),
    )
    op.add_column(
        "size_class",
        sa.Column("width", sa.Numeric(precision=4, scale=2), nullable=False),
    )
    op.add_column(
        "size_class",
        sa.Column("depth", sa.Numeric(precision=4, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("size_class", "depth")
    op.drop_column("size_class", "width")
    op.drop_column("size_class", "height")
    op.drop_column("size_class", "assigned")
    op.add_column(
        "shelves",
        sa.Column("capacity", sa.SMALLINT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "shelves",
        sa.Column("size_class_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("shelf_types_id_fkey", "shelves", type_="foreignkey")
    op.create_foreign_key(
        "shelves_size_class_id_fkey", "shelves", "size_class", ["size_class_id"], ["id"]
    )
    op.drop_column("shelves", "shelf_type_id")
    op.drop_table("shelf_types")
    # ### end Alembic commands ###
