"""shelf_type_alter_uq

Revision ID: 2024_12_16_19_34_01
Revises: 2024_12_16_14:07:39
Create Date: 2024-12-16 19:34:01.216583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_12_16_19_34_01'
down_revision: Union[str, None] = '2024_12_16_14_07_39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_type_max_cap_size_class_shelf_type', 'shelf_types', type_='unique')
    op.create_unique_constraint('uq_type_size_class_shelf_type', 'shelf_types', ['type', 'size_class_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_type_size_class_shelf_type', 'shelf_types', type_='unique')
    op.create_unique_constraint('uq_type_max_cap_size_class_shelf_type', 'shelf_types', ['type', 'max_capacity', 'size_class_id'])
    # ### end Alembic commands ###
