"""Update shelving job association table

Revision ID: 2024_02_17_21_05_55
Revises: 2024_02_06_12:41:18
Create Date: 2024-02-18 02:05:55.190444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_02_17_21_05_55'
down_revision: Union[str, None] = '2024_02_06_12_41_18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelving_job_item_associations', 'id')
    op.drop_column('shelving_job_tray_associations', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelving_job_tray_associations', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shelving_job_item_associations', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
