"""Added Batch Upload Table

Revision ID: 2024_07_27_15_55_29
Revises: 2024_07_25_16:30:47
Create Date: 2024-07-27 19:55:29.350602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.batch_upload import BatchUploadStatus

# revision identifiers, used by Alembic.
revision: str = "2024_07_27_15_55_29"
down_revision: Union[str, None] = "2024_07_25_16_30_47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("withdraw_job_id", sa.Integer(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_type", sa.String(), nullable=True),
        sa.Column("create_dt", sa.DateTime(), nullable=False),
        sa.Column("update_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["withdraw_job_id"],
            ["withdraw_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    batch_upload_enum = sa.Enum(BatchUploadStatus, name="batch_upload_status_enum")
    batch_upload_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "batch_uploads",
        sa.Column(
            "status",
            batch_upload_enum,
            nullable=True,
            server_default=BatchUploadStatus.New,
        ),
    )

    op.add_column("requests", sa.Column("batch_upload_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "requests", "batch_uploads", ["batch_upload_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.drop_column("requests", "batch_upload_id")
    op.drop_table("batch_uploads")
    # ### end Alembic commands ###
