"""user_email_auth_token

Revision ID: 2024_07_10_09_09_37
Revises: 2024_06_18_21:54:21
Create Date: 2024-07-10 09:09:37.654045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2024_07_10_09_09_37'
down_revision: Union[str, None] = '2024_06_18_21_54_21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('fetch_auth_token', sa.String(length=300), nullable=True))
    op.create_unique_constraint('uq_user_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email', 'users', type_='unique')
    op.drop_column('users', 'fetch_auth_token')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
