"""Remove Required Shelf Barcode

Revision ID: 2024_12_09_21_49_15
Revises: 2024_11_24_21:51:13
Create Date: 2024-12-10 02:49:15.625013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_12_09_21_49_15'
down_revision: Union[str, None] = '2024_11_24_21_51_13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shelves', 'barcode_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shelves', 'barcode_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ### #
