"""shelvingjob_tray

Revision ID: 2024_04_15_10_19_50
Revises: 2024_04_15_08:44:57
Create Date: 2024-04-15 09:19:50.237845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_04_15_10_19_50'
down_revision: Union[str, None] = '2024_04_15_08_44_57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trays', sa.Column('shelving_job_id', sa.Integer(), nullable=True))
    op.add_column('trays', sa.Column('shelf_position_proposed_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tray_shelving_job', 'trays', 'shelving_jobs', ['shelving_job_id'], ['id'])
    op.create_foreign_key('fk_tray_proposed_pos', 'trays', 'shelf_positions', ['shelf_position_proposed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tray_shelving_job', 'trays', type_='foreignkey')
    op.drop_constraint('fk_tray_proposed_pos', 'trays', type_='foreignkey')
    op.drop_column('trays', 'shelf_position_proposed_id')
    op.drop_column('trays', 'shelving_job_id')
    # ### end Alembic commands ###
