"""Adding refile queue dt

Revision ID: 2024_06_14_14_15_54
Revises: 2024_06_12_19:26:05
Create Date: 2024-06-14 18:15:54.194639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2024_06_14_14_15_54"
down_revision: Union[str, None] = "2024_06_12_19_26_05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("scanned_for_refile_queue_dt", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "items", sa.Column("scanned_for_refile_dt", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "non_tray_items",
        sa.Column("scanned_for_refile_queue_dt", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "non_tray_items",
        sa.Column("scanned_for_refile_dt", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("non_tray_items", "scanned_for_refile_dt")
    op.drop_column("non_tray_items", "scanned_for_refile_queue_dt")
    op.drop_column("items", "scanned_for_refile_dt")
    op.drop_column("items", "scanned_for_refile_queue_dt")
    # ### end Alembic commands ###
