"""Updating Group Permission

Revision ID: 2024_04_30_13_41_54
Revises: 2024_04_23_10:49:16
Create Date: 2024-04-30 17:41:54.055148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_04_30_13_41_54'
down_revision: Union[str, None] = '2024_04_29_09_49_57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_id', 'group_id', name='uq_permission_id_group_id')
    )
    op.drop_column('permissions', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('group_id', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_table('group_permissions')
    # ### end Alembic commands ###
