"""Added barcode and refile changes

Revision ID: 2024_08_06_21_11_16
Revises: 2024_08_06_18:46:38
Create Date: 2024-08-07 01:11:16.138843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = "2024_08_06_21_11_16"
down_revision: Union[str, None] = "2024_08_06_18_46_38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "barcodes",
        sa.Column("withdrawn", sa.Boolean(), nullable=False, server_default="False"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("barcodes", "withdrawn")
    # ### end Alembic commands ###
