"""remove_shelving_m2m_assoc

Revision ID: 2024_04_15_08_44_57
Revises: 2024_03_31_12:25:37
Create Date: 2024-04-15 07:44:57.255721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_04_15_08_44_57'
down_revision: Union[str, None] = '2024_03_31_12_25_37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelving_job_tray_associations')
    op.drop_table('shelving_job_item_associations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelving_job_item_associations',
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('shelf_position_proposed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shelf_position_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shelving_job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='shelving_job_item_associations_item_id_fkey'),
    sa.ForeignKeyConstraint(['shelf_position_id'], ['shelf_positions.id'], name='shelving_job_item_associations_shelf_position_id_fkey'),
    sa.ForeignKeyConstraint(['shelf_position_proposed_id'], ['shelf_positions.id'], name='shelving_job_item_associations_shelf_position_proposed_id_fkey'),
    sa.ForeignKeyConstraint(['shelving_job_id'], ['shelving_jobs.id'], name='shelving_job_item_associations_shelving_job_id_fkey'),
    sa.PrimaryKeyConstraint('shelving_job_id', 'item_id', name='shelving_job_item_associations_pkey')
    )
    op.create_table('shelving_job_tray_associations',
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('shelf_position_proposed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shelf_position_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shelving_job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tray_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shelf_position_id'], ['shelf_positions.id'], name='shelving_job_tray_associations_shelf_position_id_fkey'),
    sa.ForeignKeyConstraint(['shelf_position_proposed_id'], ['shelf_positions.id'], name='shelving_job_tray_associations_shelf_position_proposed_id_fkey'),
    sa.ForeignKeyConstraint(['shelving_job_id'], ['shelving_jobs.id'], name='shelving_job_tray_associations_shelving_job_id_fkey'),
    sa.ForeignKeyConstraint(['tray_id'], ['trays.id'], name='shelving_job_tray_associations_tray_id_fkey'),
    sa.PrimaryKeyConstraint('shelving_job_id', 'tray_id', name='shelving_job_tray_associations_pkey')
    )
    # ### end Alembic commands ###
