"""Removing assigned field

Revision ID: 2024_12_11_21_54_12
Revises: 2024_12_11_16:20:00
Create Date: 2024-12-12 02:54:12.976253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_12_11_21_54_12'
down_revision: Union[str, None] = '2024_12_11_16_20_00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('size_class', 'assigned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('size_class', sa.Column('assigned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
#
