"""remove_uq_proposed_constraint

Revision ID: 2024_04_15_18_12_02
Revises: 2024_04_15_18:05:21
Create Date: 2024-04-15 17:12:02.369875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_04_15_18_12_02'
down_revision: Union[str, None] = '2024_04_15_18_05_21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_non_tray_proposed_position', 'non_tray_items', type_='unique')
    op.drop_constraint('uq_tray_proposed_position', 'trays', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tray_proposed_position', 'trays', ['shelf_position_proposed_id'])
    op.create_unique_constraint('uq_non_tray_proposed_position', 'non_tray_items', ['shelf_position_proposed_id'])
    # ### end Alembic commands ###
