"""remove_sc_owner_rel

Revision ID: 2025_02_06_18_27_45
Revises: 2025_01_28_20:31:54
Create Date: 2025-02-06 18:27:45.863111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_02_06_18_27_45'
down_revision: Union[str, None] = '2025_01_28_20_31_54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners_size_classes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners_size_classes',
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size_class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name='owners_size_classes_owner_id_fkey'),
    sa.ForeignKeyConstraint(['size_class_id'], ['size_class.id'], name='owners_size_classes_size_class_id_fkey'),
    sa.PrimaryKeyConstraint('owner_id', 'size_class_id', name='owners_size_classes_pkey')
    )
    # ### end Alembic commands ###
