"""withdrawn_loc_bc_tray

Revision ID: 2025_02_23_15_11_21
Revises: 2025_02_23_10:49:47
Create Date: 2025-02-23 15:11:21.268461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_02_23_15_11_21'
down_revision: Union[str, None] = '2025_02_23_10_49_47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trays', sa.Column('withdrawn_loc_bcodes', sa.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trays', 'withdrawn_loc_bcodes')
    # ### end Alembic commands ###
