"""Updating audit log table

Revision ID: 2025_01_07_16_22_10
Revises: 2024_12_19_16:50:19
Create Date: 2025-01-07 21:22:10.269273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2025_01_07_16_22_10"
down_revision: Union[str, None] = "2025_01_07_14_55_01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_log",
        sa.Column("last_action", sa.VARCHAR(length=150), nullable=True, default=None),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_log", "last_action")
    # ### end Alembic commands ###
