"""Added Retrieval Event tables

Revision ID: 2025_01_28_20_31_54
Revises: 2025_01_28_19:18:07
Create Date: 2025-01-29 01:31:54.963768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_01_28_20_31_54'
down_revision: Union[str, None] = '2025_01_28_19_18_07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('non_tray_items_retrieval_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('non_tray_item_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('pick_list_id', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('update_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['non_tray_item_id'], ['non_tray_items.id'], name='fk_non_tray_items_retrieval_events_non_tray_item_id'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name='fk_non_tray_items_retrieval_events_owner_id'),
    sa.ForeignKeyConstraint(['pick_list_id'], ['pick_lists.id'], name='fk_non_tray_items_retrieval_events_picklist_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_retrieval_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('pick_list_id', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('update_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='fk_items_retrieval_events_item_id'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name='fk_items_retrieval_events_owner_id'),
    sa.ForeignKeyConstraint(['pick_list_id'], ['pick_lists.id'], name='fk_items_retrieval_events_picklist_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('verification_changes', 'workflow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_changes', 'workflow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('items_retrieval_events')
    op.drop_table('non_tray_items_retrieval_events')
    # ### end Alembic commands ###
#
