"""uq_container_sp

Revision ID: 2025_04_21_20_43_30
Revises: 2025_04_21_12:28:43
Create Date: 2025-04-21 20:43:30.240458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_04_21_20_43_30'
down_revision: Union[str, None] = '2025_04_21_12_28_43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_non_tray_shelf_position_id', table_name='non_tray_items')
    op.drop_index('idx_non_tray_shelf_position_proposed_id', table_name='non_tray_items')
    op.create_unique_constraint('uq_non_tray_items_shelf_position_id', 'non_tray_items', ['shelf_position_id'])
    op.drop_index('idx_tray_shelf_position_id', table_name='trays')
    op.drop_index('idx_tray_shelf_position_proposed_id', table_name='trays')
    op.create_unique_constraint('uq_trays_shelf_position_id', 'trays', ['shelf_position_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_trays_shelf_position_id', 'trays', type_='unique')
    op.create_index('idx_tray_shelf_position_proposed_id', 'trays', ['shelf_position_proposed_id'], unique=False)
    op.create_index('idx_tray_shelf_position_id', 'trays', ['shelf_position_id'], unique=False)
    op.drop_constraint('uq_non_tray_items_shelf_position_id', 'non_tray_items', type_='unique')
    op.create_index('idx_non_tray_shelf_position_proposed_id', 'non_tray_items', ['shelf_position_proposed_id'], unique=False)
    op.create_index('idx_non_tray_shelf_position_id', 'non_tray_items', ['shelf_position_id'], unique=False)
    # ### end Alembic commands ###
