"""Index Shelves

Revision ID: 2025_04_11_17_22_40
Revises: 2025_04_10_11:51:05
Create Date: 2025-04-11 21:22:40.601682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_04_11_17_22_40'
down_revision: Union[str, None] = '2025_04_10_11_51_05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql = """
        -- For Tray
        CREATE INDEX IF NOT EXISTS idx_tray_shelf_position_id ON trays(shelf_position_id);
        CREATE INDEX IF NOT EXISTS idx_tray_shelf_position_proposed_id ON trays(shelf_position_proposed_id);

        -- For NonTrayItem
        CREATE INDEX IF NOT EXISTS idx_non_tray_shelf_position_id ON non_tray_items(shelf_position_id);
        CREATE INDEX IF NOT EXISTS idx_non_tray_shelf_position_proposed_id ON non_tray_items(shelf_position_proposed_id);
    """
    op.execute(sql)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql = """
        DROP INDEX IF EXISTS idx_tray_shelf_position_id;
        DROP INDEX IF EXISTS idx_tray_shelf_position_proposed_id;
        DROP INDEX IF EXISTS idx_non_tray_shelf_position_id;
        DROP INDEX IF EXISTS idx_non_tray_shelf_position_proposed_id;
    """
    op.execute(sql)
    # ### end Alembic commands ###
