"""Update verification change Enum

Revision ID: 2025_01_28_19_18_07
Revises: 2025_01_27_19:52:01
Create Date: 2025-01-29 00:18:07.074454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.verification_changes import VerificationChangeStatus

# revision identifiers, used by Alembic.
revision: str = '2025_01_28_19_18_07'
down_revision: Union[str, None] = '2025_01_27_19_52_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE change_type_tmp AS ENUM (
            'Added', 'Removed', 'BarcodeValueEdit', 'SizeClassEdit', 'MediaTypeEdit'
        );
        """
    )
    op.execute(
        "ALTER TABLE  verification_changes ALTER COLUMN change_type TYPE change_type_tmp"
        " USING change_type::text::change_type_tmp"
        )
    op.execute("DROP TYPE change_type")
    op.execute("ALTER TYPE change_type_tmp RENAME TO change_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE change_type_tmp AS ENUM (
            'Added', 'Removed', 'SizeClassEdit', 'MediaTypeEdit'
        );
        """
    )
    op.execute(
        "ALTER TABLE  verification_changes ALTER COLUMN change_type TYPE change_type_tmp"
        " USING change_type::text::change_type_tmp"
        )
    op.execute("DROP TYPE change_type")
    op.execute("ALTER TYPE change_type_tmp RENAME TO change_type")

    # ### end Alembic commands ###
#
