"""Update ShelvingJobDiscrepancy table

Revision ID: 2025_04_07_14_59_52
Revises: 2025_03_19_14:02:01
Create Date: 2025-04-07 18:59:52.636944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2025_04_07_14_59_52'
down_revision: Union[str, None] = '2025_03_19_14_02_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shelving_job_discrepancies', 'shelving_job_id', nullable=True,
                    server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('shelving_job_discrepancies', 'shelving_job_id', nullable=False)
    # ### end Alembic commands ###
#
