"""Updating RefileNonTrayItem table

Revision ID: 2025_04_09_09_43_23
Revises: 2025_03_19_14:02:01
Create Date: 2025-04-09 13:43:23.950472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2025_04_09_09_43_23"
down_revision: Union[str, None] = "2025_04_07_14_59_52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a primary key constraint on the existing 'id' column
    op.drop_constraint(
        "refile_non_tray_items_pkey", "refile_non_tray_items", type_="primary"
    )
    op.create_primary_key(
        "refile_non_tray_items_pkey",
        "refile_non_tray_items",
        ["non_tray_item_id", "refile_job_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "refile_non_tray_items_pkey", "refile_non_tray_items", type_="primary"
    )
    op.create_primary_key(
        "refile_non_tray_items_pkey", "refile_non_tray_items", ["non_tray_item_id"]
    )
    # ### end Alembic commands ###


#
