"""Updating scanned_for_refile field

Revision ID: 2025_04_24_18_29_11
Revises: 8d08a42236e8
Create Date: 2025-04-24 22:29:11.160836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_04_24_18_29_11'
down_revision: Union[str, None] = '8d08a42236e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('scanned_for_refile', sa.Boolean(), nullable=True, server_default=None))
    op.add_column('items', sa.Column('scanned_for_refile_dt', sa.TIMESTAMP(timezone=True), nullable=True, server_default=None))
    op.add_column('non_tray_items', sa.Column('scanned_for_refile', sa.Boolean(), nullable=True, server_default=None))
    op.add_column('non_tray_items', sa.Column('scanned_for_refile_dt', sa.TIMESTAMP(timezone=True), nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('non_tray_items', 'scanned_for_refile_dt')
    op.drop_column('non_tray_items', 'scanned_for_refile')
    op.drop_column('items', 'scanned_for_refile_dt')
    op.drop_column('items', 'scanned_for_refile')
    # ### end Alembic commands ###
#
