"""Add default_building_id to User

Revision ID: 2026_02_21_01_32_09
Revises: 2026_02_17_21_42_00
Create Date: 2026-02-20 20:32:09.624846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_02_21_01_32_09'
down_revision: Union[str, None] = '2026_02_17_21_42_00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_building_id', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'buildings', ['default_building_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_building_id')
    # ### end Alembic commands ###
