"""Add destination_tray_id to shelving_job_containers

Revision ID: 2026_01_24_15_00_46
Revises: b2c3d4e5f6g7
Create Date: 2026-01-24 15:00:46.958681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_01_24_15_00_46'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('shelving_job_containers', sa.Column('destination_tray_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'shelving_job_containers', 'trays', ['destination_tray_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_constraint(None, 'shelving_job_containers', type_='foreignkey')
    op.drop_column('shelving_job_containers', 'destination_tray_id')
    # ### end Alembic commands ###
