"""Add Side table

Revision ID: 2023_10_15_07_05_03
Revises: 2023_10_15_07:03:48
Create Date: 2023-10-15 06:05:03.438944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_10_15_07_05_03'
down_revision: Union[str, None] = '2023_10_15_07_03_48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aisle_id', sa.Integer(), nullable=False),
    sa.Column('side_orientation_id', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aisle_id'], ['aisles.id'], ),
    sa.ForeignKeyConstraint(['side_orientation_id'], ['side_orientations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sides')
    # ### end Alembic commands ###
