"""Add owner to shelf

Revision ID: 2023_11_27_11_26_47
Revises: 2023_11_27_10:01:55
Create Date: 2023-11-27 10:26:47.459866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_11_27_11_26_47'
down_revision: Union[str, None] = '2023_11_27_10_01_55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelves', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shelves', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shelves', type_='foreignkey')
    op.drop_column('shelves', 'owner_id')
    # ### end Alembic commands ###
