"""Update aisles,sides,orientations,modules,buildings

Revision ID: 2023_10_15_12_21_17
Revises: 2023_10_15_07:05:03
Create Date: 2023-10-15 11:21:17.838575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_10_15_12_21_17'
down_revision: Union[str, None] = '2023_10_15_07_05_03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aisles', 'number',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('aisles', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('modules', 'module_number_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('side_orientations', 'name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=5),
               nullable=False)
    op.add_column('sides', sa.Column('barcode', sa.dialects.postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sides', 'barcode')
    op.alter_column('side_orientations', 'name',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('modules', 'module_number_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('aisles', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('aisles', 'number',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
