"""Normalize aisle number

Revision ID: 2023_10_16_10_00_05
Revises: 2023_10_15_12:21:17
Create Date: 2023-10-16 09:00:05.411845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_10_16_10_00_05'
down_revision: Union[str, None] = '2023_10_15_12_21_17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aisle_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.add_column('aisles', sa.Column('aisle_number_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_building_module_aisle_number_id', 'aisles', ['building_id', 'module_id', 'aisle_number_id'])
    op.create_foreign_key(None, 'aisles', 'aisle_numbers', ['aisle_number_id'], ['id'])
    op.drop_column('aisles', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aisles', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'aisles', type_='foreignkey')
    op.drop_constraint('uq_building_module_aisle_number_id', 'aisles', type_='unique')
    op.drop_column('aisles', 'aisle_number_id')
    op.drop_table('aisle_numbers')
    # ### end Alembic commands ###
