"""ladder unique_together side_ladder_number

Revision ID: 2023_11_05_16_26_32
Revises: 2023_11_05_14:57:19
Create Date: 2023-11-05 15:26:32.180810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_11_05_16_26_32'
down_revision: Union[str, None] = '2023_11_05_14_57_19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_side_id_ladder_number_id', 'ladders', ['side_id', 'ladder_number_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_side_id_ladder_number_id', 'ladders', type_='unique')
    # ### end Alembic commands ###
