"""Unique constraint orientation name

Revision ID: 2023_10_16_10_18_17
Revises: 2023_10_16_10:00:05
Create Date: 2023-10-16 09:18:17.611483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2023_10_16_10_18_17'
down_revision: Union[str, None] = '2023_10_16_10_00_05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_side_orientation_name', 'side_orientations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_side_orientation_name', 'side_orientations', type_='unique')
    # ### end Alembic commands ###
