"""Adding ID to Refileitems

Revision ID: 2024_08_06_18_46_38
Revises: 2024_08_06_13:14:38
Create Date: 2024-08-06 22:46:38.530414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = "2024_08_06_18_46_38"
down_revision: Union[str, None] = "2024_08_06_13_14_38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refile_items", sa.Column("id", sa.Integer(), nullable=False, primary_key=True)
    )
    op.add_column("refile_items", sa.Column("create_dt", sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
    op.add_column("refile_items", sa.Column("update_dt", sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
    op.add_column(
        "refile_non_tray_items",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
    )
    op.add_column(
        "refile_non_tray_items", sa.Column("create_dt", sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp())
    )
    op.add_column(
        "refile_non_tray_items", sa.Column("update_dt", sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp())
    )
    op.alter_column(
        "refile_non_tray_items",
        "refile_job_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint("uq_item_id_refile_job_id", "refile_items", type_="unique")
    op.create_unique_constraint(
        "uq_item_id_refile_job_id", "refile_items", ["item_id", "refile_job_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refile_non_tray_items",
        "refile_job_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_column("refile_non_tray_items", "update_dt")
    op.drop_column("refile_non_tray_items", "create_dt")
    op.drop_column("refile_non_tray_items", "id")
    op.drop_column("refile_items", "update_dt")
    op.drop_column("refile_items", "create_dt")
    op.drop_column("refile_items", "id")
    # ### end Alembic commands ###
