"""Updating size class field

Revision ID: 2024_03_01_16_54_20
Revises: 2024_02_23_18:28:49
Create Date: 2024-03-01 21:54:20.050167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = "2024_03_01_16_54_20"
down_revision: Union[str, None] = "2024_02_28_14_04_47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "size_class",
        "name",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "size_class",
        "name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=25),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
