"""shelvingjob_building

Revision ID: 2024_04_17_11_42_46
Revises: 2024_04_15_18:12:02
Create Date: 2024-04-17 10:42:46.234020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_04_17_11_42_46'
down_revision: Union[str, None] = '2024_04_15_18_12_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelving_jobs', sa.Column('building_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_shelvingjob_building_id', 'shelving_jobs', 'buildings', ['building_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shelvingjob_building_id', 'shelving_jobs', type_='foreignkey')
    op.drop_column('shelving_jobs', 'building_id')
    # ### end Alembic commands ###
