"""pick_list_support

Revision ID: 2024_06_10_09_05_29
Revises: 2024_05_21_12:12:55
Create Date: 2024-06-10 08:05:29.218689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_06_10_09_05_29'
down_revision: Union[str, None] = '2024_05_21_12_12_55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Created', 'Paused', 'Running', 'Completed', name='pick_list_status'), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('last_transition', sa.DateTime(), nullable=True),
    sa.Column('run_time', sa.Interval(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pick_list_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('pick_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pick_list_id'], ['pick_lists.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'pick_list_id', name='uq_request_id_pick_list_id')
    )
    op.add_column('aisles', sa.Column('sort_priority', sa.Integer(), nullable=True))
    op.add_column('ladders', sa.Column('sort_priority', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('building_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('scanned_for_pick_list', sa.Boolean(), nullable=False, server_default="False"))
    op.add_column('requests', sa.Column('scanned_for_retrieval', sa.Boolean(), nullable=False, server_default="False"))
    op.create_foreign_key('fk_requests_building', 'requests', 'buildings', ['building_id'], ['id'])
    op.add_column('shelves', sa.Column('sort_priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelves', 'sort_priority')
    op.drop_constraint('fk_requests_building', 'requests', type_='foreignkey')
    op.drop_column('requests', 'scanned_for_retrieval')
    op.drop_column('requests', 'scanned_for_pick_list')
    op.drop_column('requests', 'building_id')
    op.drop_column('ladders', 'sort_priority')
    op.drop_column('aisles', 'sort_priority')
    op.drop_table('pick_list_requests')
    op.drop_table('pick_lists')
    # ### end Alembic commands ###
