"""location_memory

Revision ID: 2024_10_24_16_04_48
Revises: 2024_10_16_12:33:26
Create Date: 2024-10-24 20:04:48.274236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2024_10_24_16_04_48'
down_revision: Union[str, None] = '2024_10_16_12_33_26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accession_jobs', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('accession_jobs', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('accession_jobs', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('aisle_numbers', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('aisle_numbers', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('aisles', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('aisles', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('barcode_types', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('barcode_types', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('barcodes', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('barcodes', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('batch_uploads', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('batch_uploads', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('buildings', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('buildings', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('container_types', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('container_types', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('conveyance_bins', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('conveyance_bins', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('delivery_locations', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('delivery_locations', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('groups', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('groups', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('item_withdrawals', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('item_withdrawals', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('items', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('items', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ladder_numbers', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ladder_numbers', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ladders', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ladders', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('media_types', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('media_types', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('modules', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('modules', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('non_tray_item_withdrawals', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('non_tray_item_withdrawals', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('non_tray_items', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('non_tray_items', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('owner_tiers', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('owner_tiers', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('owners', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('owners', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('permissions', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('permissions', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pick_lists', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pick_lists', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pick_lists', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('priorities', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('priorities', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('refile_items', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refile_items', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refile_jobs', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('refile_jobs', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('refile_jobs', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('refile_non_tray_items', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refile_non_tray_items', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('request_types', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('request_types', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('requests', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('requests', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelf_numbers', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelf_numbers', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelf_position_numbers', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelf_position_numbers', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelf_positions', 'location',
               existing_type=sa.VARCHAR(length=75),
               type_=sa.String(length=175),
               existing_nullable=True)
    op.alter_column('shelf_positions', 'internal_location',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('shelf_positions', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelf_positions', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelves', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelves', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelving_jobs', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelving_jobs', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelving_jobs', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('side_orientations', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('side_orientations', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sides', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sides', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('size_class', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('size_class', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subcollections', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subcollections', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tray_withdrawals', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tray_withdrawals', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('trays', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('trays', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('verification_jobs', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('verification_jobs', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('verification_jobs', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('withdraw_jobs', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('withdraw_jobs', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('withdraw_jobs', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workflow', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workflow', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workflow', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('withdraw_jobs', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('withdraw_jobs', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('withdraw_jobs', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('verification_jobs', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('verification_jobs', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('verification_jobs', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('trays', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('trays', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tray_withdrawals', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tray_withdrawals', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subcollections', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subcollections', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('size_class', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('size_class', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sides', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sides', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('side_orientations', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('side_orientations', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelving_jobs', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelving_jobs', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelving_jobs', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelves', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelves', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelf_positions', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelf_positions', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelf_positions', 'internal_location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('shelf_positions', 'location',
               existing_type=sa.String(length=175),
               type_=sa.VARCHAR(length=75),
               existing_nullable=True)
    op.alter_column('shelf_position_numbers', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelf_position_numbers', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelf_numbers', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelf_numbers', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('requests', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('requests', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('request_types', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('request_types', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('refile_non_tray_items', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refile_non_tray_items', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refile_jobs', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('refile_jobs', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('refile_jobs', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('refile_items', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refile_items', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('priorities', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('priorities', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pick_lists', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pick_lists', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pick_lists', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('permissions', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('permissions', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('owners', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('owners', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('owner_tiers', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('owner_tiers', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('non_tray_items', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('non_tray_items', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('non_tray_item_withdrawals', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('non_tray_item_withdrawals', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('modules', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('modules', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('media_types', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('media_types', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ladders', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ladders', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ladder_numbers', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ladder_numbers', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('items', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('items', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('item_withdrawals', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('item_withdrawals', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('groups', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('groups', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('delivery_locations', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('delivery_locations', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('conveyance_bins', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('conveyance_bins', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('container_types', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('container_types', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('buildings', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('buildings', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('batch_uploads', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('batch_uploads', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('barcodes', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('barcodes', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('barcode_types', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('barcode_types', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('aisles', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('aisles', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('aisle_numbers', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('aisle_numbers', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('accession_jobs', 'update_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('accession_jobs', 'create_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('accession_jobs', 'last_transition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###2024_10_24_16:04:48_location_memory.py
