"""remove_building_from_aisles

Revision ID: 2024_07_17_07_36_41
Revises: 2024_07_11_15:19:45
Create Date: 2024-07-17 07:36:41.742060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2024_07_17_07_36_41'
down_revision: Union[str, None] = '2024_07_11_15_19_45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_building_aisle_number_id", "aisles", type_="unique")
    op.drop_constraint("aisles_building_id_fkey", "aisles", type_="foreignkey")
    op.drop_column("aisles", "building_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aisles",
        sa.Column("building_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "aisles_building_id_fkey", "aisles", "buildings", ["building_id"], ["id"]
    )
    op.create_unique_constraint(
        "uq_building_aisle_number_id", "aisles", ["building_id", "aisle_number_id"]
    )
    # ### end Alembic commands ###
