"""Added shelf available space

Revision ID: 2024_08_06_21_32_59
Revises: 2024_08_06_18:46:38
Create Date: 2024-08-07 01:32:59.695295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = "2024_08_06_21_32_59"
down_revision: Union[str, None] = "2024_08_06_21_11_16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shelves",
        sa.Column("available_space", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shelves", "available_space")
    # ### end Alembic commands ###
