"""workflow

Revision ID: 2024_08_06_13_14_38
Revises: 2024_07_31_20:51:58
Create Date: 2024-08-06 13:14:38.679874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2024_08_06_13_14_38'
down_revision: Union[str, None] = '2024_07_31_20_51_58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accession_jobs', sa.Column('workflow_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_acc_job_workflow', 'accession_jobs', 'workflow', ['workflow_id'], ['id'])
    op.add_column('verification_jobs', sa.Column('workflow_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_ver_job_workflow', 'verification_jobs', 'workflow', ['workflow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ver_job_workflow', 'verification_jobs', type_='foreignkey')
    op.drop_column('verification_jobs', 'workflow_id')
    op.drop_constraint('fk_acc_job_workflow', 'accession_jobs', type_='foreignkey')
    op.drop_column('accession_jobs', 'workflow_id')
    op.drop_table('workflow')
    # ### end Alembic commands ###
