"""auth_expiration

Revision ID: 2024_07_25_16_30_47
Revises: 2024_07_17_12:52:38
Create Date: 2024-07-25 16:30:47.828064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2024_07_25_16_30_47'
down_revision: Union[str, None] = '2024_07_17_12_52_38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fetch_auth_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fetch_auth_expiration')
    # ### end Alembic commands ###
