"""items

Revision ID: 2024_01_23_13_23_03
Revises: 2024_01_10_08:36:41
Create Date: 2024-01-23 12:23:03.933410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_01_23_13_23_03'
down_revision: Union[str, None] = '2024_01_10_08_36_41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcollections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('tray_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=4000), nullable=True),
    sa.Column('volume', sa.String(length=15), nullable=True),
    sa.Column('condition', sa.String(length=30), nullable=True),
    sa.Column('arbitrary_data', sa.String(length=255), nullable=True),
    sa.Column('subcollection_id', sa.Integer(), nullable=True),
    sa.Column('accession_job_id', sa.Integer(), nullable=True),
    sa.Column('verification_job_id', sa.Integer(), nullable=True),
    sa.Column('accession_dt', sa.DateTime(), nullable=True),
    sa.Column('withdrawal_dt', sa.DateTime(), nullable=True),
    sa.Column('media_type_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accession_job_id'], ['accession_jobs.id'], ),
    sa.ForeignKeyConstraint(['barcode_id'], ['barcodes.id'], ),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_types.id'], ),
    sa.ForeignKeyConstraint(['subcollection_id'], ['subcollections.id'], ),
    sa.ForeignKeyConstraint(['tray_id'], ['trays.id'], ),
    sa.ForeignKeyConstraint(['verification_job_id'], ['verification_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('subcollections')
    # ### end Alembic commands ###
