"""non_tray_scanned_for_accession

Revision ID: 2024_03_15_15_22_10
Revises: 2024_03_15_15:16:21
Create Date: 2024-03-15 14:22:10.203905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_03_15_15_22_10'
down_revision: Union[str, None] = '2024_03_15_15_16_21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('non_tray_items', sa.Column('scanned_for_accession', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('non_tray_items', 'scanned_for_accession')
    # ### end Alembic commands ###
