"""Added last_transition to refilejob

Revision ID: 2024_06_18_13_47_03
Revises: 2024_06_14_14:15:54
Create Date: 2024-06-18 17:47:03.776076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2024_06_18_13_47_03"
down_revision: Union[str, None] = "2024_06_14_14_15_54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refile_jobs", sa.Column("last_transition", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refile_jobs", "last_transition")
    # ### end Alembic commands ###
