"""accession_size_class

Revision ID: 2024_03_21_16_31_23
Revises: 2024_03_15_16:32:03
Create Date: 2024-03-21 15:31:23.084719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_03_21_16_31_23'
down_revision: Union[str, None] = '2024_03_15_16_32_03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accession_jobs', sa.Column('size_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key("accession_job_size_class", 'accession_jobs', 'size_class', ['size_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("accession_job_size_class", 'accession_jobs', type_='foreignkey')
    op.drop_column('accession_jobs', 'size_class_id')
    # ### end Alembic commands ###
