"""scannedverification

Revision ID: 2024_03_28_10_27_07
Revises: 2024_03_22_09:28:10
Create Date: 2024-03-28 09:27:07.592809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_03_28_10_27_07'
down_revision: Union[str, None] = '2024_03_25_13_10_09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('scanned_for_verification', sa.Boolean(), nullable=False))
    op.add_column('non_tray_items', sa.Column('scanned_for_verification', sa.Boolean(), nullable=False))
    op.add_column('trays', sa.Column('scanned_for_verification', sa.Boolean(), nullable=False))
    op.add_column('trays', sa.Column('collection_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trays', 'collection_verified')
    op.drop_column('trays', 'scanned_for_verification')
    op.drop_column('non_tray_items', 'scanned_for_verification')
    op.drop_column('items', 'scanned_for_verification')
    # ### end Alembic commands ###
