"""Updating enum fields

Revision ID: 2024_04_29_09_49_57
Revises: 2024_04_23_10:49:16
Create Date: 2024-04-29 13:49:57.824685

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from app.models.accession_jobs import AccessionJobStatus
from app.models.items import ItemStatus
from app.models.non_tray_items import NonTrayItemStatus
from app.models.shelving_jobs import ShelvingJobStatus
from app.models.verification_jobs import VerificationJobStatus

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = "2024_04_29_09_49_57"
down_revision: Union[str, None] = "2024_04_23_10_49_16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    accession_job_status_enum = postgresql.ENUM(
        AccessionJobStatus, name="accession_status"
    )
    accession_job_status_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column("accession_jobs", "status", type_=accession_job_status_enum)

    item_status_enum = postgresql.ENUM(ItemStatus, name="item_status")
    item_status_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column("items", "status", type_=item_status_enum)

    non_tray_item_status_enum = postgresql.ENUM(
        NonTrayItemStatus, name="non_tray_item_status"
    )
    non_tray_item_status_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column("non_tray_items", "status", type_=non_tray_item_status_enum)

    shelving_job_status_enum = postgresql.ENUM(
        ShelvingJobStatus, name="shelving_status"
    )
    shelving_job_status_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column("shelving_jobs", "status", type_=shelving_job_status_enum)

    verification_job_status_enum = postgresql.ENUM(
        VerificationJobStatus, name="verification_status"
    )
    verification_job_status_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column("verification_jobs", "status", type_=verification_job_status_enum)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accession_jobs",
        "status",
        type_=postgresql.ENUM(
            "Created",
            "Paused",
            "Running",
            "Cancelled",
            "Completed",
            "Verified",
            name="accession_job_status",
        ),
        existing_server_default="Created",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "status",
        type_=postgresql.ENUM("In", "Out", name="item_status"),
        existing_server_default="Created",
        existing_nullable=False,
    )
    op.alter_column(
        "non_tray_items",
        "status",
        type_=postgresql.ENUM("In", "Out", name="non_tray_item_status"),
        existing_server_default="in",
        existing_nullable=False,
    )
    op.alter_column(
        "shelving_jobs",
        "status",
        type_=postgresql.ENUM(
            "Created",
            "Paused",
            "Running",
            "Cancelled",
            "Completed",
            name="shelving_status",
        ),
        existing_server_default="Created",
        existing_nullable=False,
    )
    op.alter_column(
        "verification_jobs",
        "status",
        type_=postgresql.ENUM(
            "Created", "Paused", "Running", "Cancelled", name="verification_status"
        ),
        existing_server_default="Created",
        existing_nullable=False,
    )

    # ### end Alembic commands ###
