"""conveyance

Revision ID: 2024_01_10_08_36_41
Revises: 2024_01_10_08:09:01
Create Date: 2024-01-10 07:36:41.412566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_01_10_08_36_41'
down_revision: Union[str, None] = '2024_01_10_08_09_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conveyance_bins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['barcode_id'], ['barcodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trays', sa.Column('conveyance_bin_id', sa.Integer(), nullable=True))
    op.create_foreign_key('tray_conveyance_bin_fk', 'trays', 'conveyance_bins', ['conveyance_bin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tray_conveyance_bin_fk', 'trays', type_='foreignkey')
    op.drop_column('trays', 'conveyance_bin_id')
    op.drop_table('conveyance_bins')
    # ### end Alembic commands ###
