"""Added status items non tray

Revision ID: 2024_03_05_14_30_35
Revises: 2024_03_01_16:54:20
Create Date: 2024-03-05 19:30:35.234010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = "2024_03_05_14_30_35"
down_revision: Union[str, None] = "2024_03_01_16_54_20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE item_status AS ENUM ('In', 'Out')")
    op.add_column('items', sa.Column('status', sa.Enum('In', 'Out',
                                                       name='item_status'), nullable=True)),

    op.execute("CREATE TYPE non_tray_item_status AS ENUM ('In', 'Out')")
    op.add_column(
        "non_tray_items",
        sa.Column(
            "status",
            sa.Enum("In", "Out", name="non_tray_item_status"),
            nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE item_status")
    op.drop_column("non_tray_items", "status")
    op.execute("DROP TYPE non_tray_item_status")
    op.drop_column("items", "status")
    # ### end Alembic commands ###
