"""Removing Cancel Verificationjob

Revision ID: 2024_02_28_14_04_47
Revises: 2024_02_23_18:28:49
Create Date: 2024-02-28 19:04:47.845047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = "2024_02_28_14_04_47"
down_revision: Union[str, None] = "2024_02_23_18_28_49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verification_jobs", "status")
    op.add_column(
        "verification_jobs",
        sa.Column(
            "status",
            sa.Enum(
                "Created",
                "Paused",
                "Running",
                "Completed",
                name="verification_status",
            ),
            nullable=True,
        ),
    ),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verification_jobs", "status")
    op.add_column(
        "verification_jobs",
        sa.Column(
            "status",
            sa.Enum(
                "Created",
                "Paused",
                "Running",
                "Cancelled",
                "Completed",
                name="verification_status",
            ),
            nullable=True,
        ),
    ),
    # ### end Alembic commands ###
