"""scanned_for_shelving

Revision ID: 2024_04_22_16_35_56
Revises: 2024_04_17_11:42:46
Create Date: 2024-04-22 15:35:56.597516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_04_22_16_35_56'
down_revision: Union[str, None] = '2024_04_17_11_42_46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('non_tray_items', sa.Column('scanned_for_shelving', sa.Boolean(), nullable=False, server_default="False"))
    op.add_column('trays', sa.Column('scanned_for_shelving', sa.Boolean(), nullable=False, server_default="False"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trays', 'scanned_for_shelving')
    op.drop_column('non_tray_items', 'scanned_for_shelving')
    # ### end Alembic commands ###
