"""shelvingjob_nontray

Revision ID: 2024_04_15_11_44_30
Revises: 2024_04_15_10:19:50
Create Date: 2024-04-15 10:44:30.330123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2024_04_15_11_44_30'
down_revision: Union[str, None] = '2024_04_15_10_19_50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('non_tray_items', sa.Column('shelving_job_id', sa.Integer(), nullable=True))
    op.add_column('non_tray_items', sa.Column('shelf_position_id', sa.Integer(), nullable=True))
    op.add_column('non_tray_items', sa.Column('shelf_position_proposed_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_nontray_shelving_job_id', 'non_tray_items', 'shelving_jobs', ['shelving_job_id'], ['id'])
    op.create_foreign_key('fk_nontray_shelf_proposed_position_id', 'non_tray_items', 'shelf_positions', ['shelf_position_proposed_id'], ['id'])
    op.create_foreign_key('fk_nontray_shelf_position_id', 'non_tray_items', 'shelf_positions', ['shelf_position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_nontray_shelving_job_id', 'non_tray_items', type_='foreignkey')
    op.drop_constraint('fk_nontray_shelf_proposed_position_id', 'non_tray_items', type_='foreignkey')
    op.drop_constraint('fk_nontray_shelf_position_id', 'non_tray_items', type_='foreignkey')
    op.drop_column('non_tray_items', 'shelf_position_proposed_id')
    op.drop_column('non_tray_items', 'shelf_position_id')
    op.drop_column('non_tray_items', 'shelving_job_id')
    # ### end Alembic commands ###
