"""expand2_s_j_discrep

Revision ID: 2025_01_07_14_55_01
Revises: 2025_01_07_14:51:50
Create Date: 2025-01-07 14:55:01.934100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_01_07_14_55_01'
down_revision: Union[str, None] = '2025_01_07_14_51_50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelving_job_discrepancies', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('shelving_job_discrepancies_user_id_fkey', 'shelving_job_discrepancies', type_='foreignkey')
    op.create_foreign_key("fk_s_j_d_user_id", 'shelving_job_discrepancies', 'users', ['assigned_user_id'], ['id'])
    op.drop_column('shelving_job_discrepancies', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelving_job_discrepancies', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint("fk_s_j_d_user_id", 'shelving_job_discrepancies', type_='foreignkey')
    op.create_foreign_key('shelving_job_discrepancies_user_id_fkey', 'shelving_job_discrepancies', 'users', ['user_id'], ['id'])
    op.drop_column('shelving_job_discrepancies', 'assigned_user_id')
    # ### end Alembic commands ###
