"""nt_shelved_dt_

Revision ID: 2025_01_20_08_03_38
Revises: 2025_01_18_21:02:44
Create Date: 2025-01-20 08:03:38.257198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_01_20_08_03_38'
down_revision: Union[str, None] = '2025_01_18_21_02_44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('non_tray_items', sa.Column('shelved_dt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('non_tray_items', 'shelved_dt')
    # ### end Alembic commands ###
