"""withdrawn_loc_bcodes

Revision ID: 2025_02_23_10_49_47
Revises: 2025_02_18_08:31:03
Create Date: 2025-02-23 10:49:47.794950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_02_23_10_49_47'
down_revision: Union[str, None] = '2025_02_18_08_31_03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('withdrawn_loc_bcodes', sa.VARCHAR(length=150), nullable=True))
    op.add_column('non_tray_items', sa.Column('withdrawn_loc_bcodes', sa.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('non_tray_items', 'withdrawn_loc_bcodes')
    op.drop_column('items', 'withdrawn_loc_bcodes')
    # ### end Alembic commands ###
