"""withdrawn_loc

Revision ID: 2025_02_18_08_31_03
Revises: 2025_02_13_01:19:51
Create Date: 2025-02-18 08:31:03.963033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_02_18_08_31_03'
down_revision: Union[str, None] = '2025_02_13_01_19_51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('withdrawn_location', sa.VARCHAR(length=175), nullable=True))
    op.add_column('items', sa.Column('withdrawn_internal_location', sa.VARCHAR(length=200), nullable=True))
    op.add_column('non_tray_items', sa.Column('withdrawn_location', sa.VARCHAR(length=175), nullable=True))
    op.add_column('non_tray_items', sa.Column('withdrawn_internal_location', sa.VARCHAR(length=200), nullable=True))
    op.add_column('trays', sa.Column('withdrawn_location', sa.VARCHAR(length=175), nullable=True))
    op.add_column('trays', sa.Column('withdrawn_internal_location', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trays', 'withdrawn_internal_location')
    op.drop_column('trays', 'withdrawn_location')
    op.drop_column('non_tray_items', 'withdrawn_internal_location')
    op.drop_column('non_tray_items', 'withdrawn_location')
    op.drop_column('items', 'withdrawn_internal_location')
    op.drop_column('items', 'withdrawn_location')
    # ### end Alembic commands ###
