"""Added verificationchange table

Revision ID: 2025_01_27_19_52_01
Revises: 2025_01_20_08:03:38
Create Date: 2025-01-28 00:52:01.015400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.verification_changes import VerificationChangeStatus



# revision identifiers, used by Alembic.
revision: str = '2025_01_27_19_52_01'
down_revision: Union[str, None] = '2025_01_20_08_03_38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('tray_barcode_value', sa.String(), nullable=True),
    sa.Column('item_barcode_value', sa.String(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('update_dt', sa.DateTime(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(item_barcode_value IS NOT NULL AND '
                       'tray_barcode_value IS NULL) OR (item_barcode_value IS NOT NULL '
                       'AND tray_barcode_value IS NOT NULL)',
                       name='ck_item_xor_tray'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], name='fk_verification_changes_completed_by_id_users'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'],
                            name='fk_verification_changes_workflow_id_verification_jobs'),
    sa.PrimaryKeyConstraint('id')
    )
    verification_change_enum = sa.Enum(
        VerificationChangeStatus, name="change_type"
    )
    verification_change_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "verification_changes",
        sa.Column(
            "change_type",
            verification_change_enum,
            nullable=True,
            server_default=None,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_item_xor_tray", 'verification_changes', type_='check')
    op.drop_constraint('fk_verification_changes_workflow_id_verification_jobs', 'verification_changes', type_='foreignkey')
    op.drop_constraint('fk_verification_changes_completed_by_id_users', 'verification_changes', type_='foreignkey')
    op.drop_table('verification_changes')
    # ### end Alembic commands ###
#
