"""sc_short_increase

Revision ID: 2025_01_17_01_40_55
Revises: 2025_01_07_16:22:10
Create Date: 2025-01-17 01:40:55.528630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_01_17_01_40_55'
down_revision: Union[str, None] = '2025_01_07_16_22_10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('size_class', 'short_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('size_class', 'short_name',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
