"""index_more_coluns

Revision ID: 2025_01_18_21_02_44
Revises: 2025_01_17_01:40:55
Create Date: 2025-01-18 21:02:44.972244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_01_18_21_02_44'
down_revision: Union[str, None] = '2025_01_17_01_40_55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_barcode_types_allowed_pattern'), 'barcode_types', ['allowed_pattern'], unique=False)
    op.create_index(op.f('ix_owners_name'), 'owners', ['name'], unique=False)
    op.create_index(op.f('ix_shelf_types_type'), 'shelf_types', ['type'], unique=False)
    op.create_index(op.f('ix_side_orientations_name'), 'side_orientations', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_side_orientations_name'), table_name='side_orientations')
    op.drop_index(op.f('ix_shelf_types_type'), table_name='shelf_types')
    op.drop_index(op.f('ix_owners_name'), table_name='owners')
    op.drop_index(op.f('ix_barcode_types_allowed_pattern'), table_name='barcode_types')
    # ### end Alembic commands ###
