"""store_av_space_again

Revision ID: 2025_02_08_19_01_09
Revises: 2025_02_06_18:27:45
Create Date: 2025-02-08 19:01:09.972330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '2025_02_08_19_01_09'
down_revision: Union[str, None] = '2025_02_06_18_27_45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelves', sa.Column(
        'available_space',
        sa.Integer(),
        nullable=False,
        server_default="0"
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelves', 'available_space')
    # ### end Alembic commands ###
