"""Add item_id to shelving_job_containers

Revision ID: 2026_01_24_15_04_33
Revises: 2026_01_24_15_00_46
Create Date: 2026-01-24 15:04:33.263687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_01_24_15_04_33'
down_revision: Union[str, None] = '2026_01_24_15_00_46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('shelving_job_containers', sa.Column('item_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'shelving_job_containers', 'items', ['item_id'], ['id'])
    
    # Update Check Constraint
    # Note: Alembic doesn't always support drop_constraint by name easily if it wasn't named explicitly in DB 
    # but we named it in the previous model definition. 
    # We try to drop it. If it fails (doesn't exist), we might need conditional logic, 
    # but assuming consistency it should exist.
    try:
        op.drop_constraint('ck_shelving_job_container_tray_xor_non_tray', 'shelving_job_containers', type_='check')
    except Exception:
        pass # Ignore if not found (or handle appropriately)
        
    op.create_check_constraint(
        'ck_shelving_job_container_tray_xor_non_tray_xor_item',
        'shelving_job_containers',
        '(tray_id IS NOT NULL) OR (non_tray_item_id IS NOT NULL) OR (item_id IS NOT NULL)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_constraint('ck_shelving_job_container_tray_xor_non_tray_xor_item', 'shelving_job_containers', type_='check')
    op.create_check_constraint(
        'ck_shelving_job_container_tray_xor_non_tray',
        'shelving_job_containers',
        '(tray_id IS NOT NULL) OR (non_tray_item_id IS NOT NULL)'
    )
    
    op.drop_constraint(None, 'shelving_job_containers', type_='foreignkey')
    op.drop_column('shelving_job_containers', 'item_id')
    # ### end Alembic commands ###
