# /app/models/scheduled_exports.py

import enum
import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import BigInteger, TIMESTAMP, ForeignKey, Boolean, Integer, String
from sqlalchemy.dialects.postgresql import JSONB

from typing import Optional, List
from datetime import datetime
from app.database.base import Base


class ScheduleType(str, enum.Enum):
    """Python enum for schedule type values."""
    ONCE = "once"
    RECURRING = "recurring"


class ExportFrequency(str, enum.Enum):
    """Python enum for export frequency values."""
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"


class ExportStatus(str, enum.Enum):
    """Python enum for export status values."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class ScheduledExport(Base):
    """
    Configuration for a scheduled raw data export.
    """
    __tablename__ = "scheduled_exports"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    dataset: Mapped[str] = mapped_column(String(50), nullable=False)
    filters: Mapped[dict] = mapped_column(JSONB, nullable=True)

    schedule_type: Mapped[str] = mapped_column(
        sa.Enum("once", "recurring", name="schedule_type"),
        default="once"
    )
    frequency: Mapped[Optional[str]] = mapped_column(
        sa.Enum("daily", "weekly", "monthly", name="export_frequency"),
        nullable=True
    )

    retention_days: Mapped[int] = mapped_column(Integer, default=7)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)

    last_run_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    next_run_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True), nullable=True)

    # Relationships
    history: Mapped[List["ExportHistory"]] = relationship(back_populates="scheduled_export", cascade="all, delete-orphan")


class ExportHistory(Base):
    """
    Tracks actual files generated by exports.
    """
    __tablename__ = "export_history"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    scheduled_export_id: Mapped[Optional[int]] = mapped_column(ForeignKey("scheduled_exports.id"), nullable=True)

    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    file_path: Mapped[str] = mapped_column(String(512), nullable=False)

    status: Mapped[str] = mapped_column(
        sa.Enum("pending", "running", "completed", "failed", name="export_status"),
        default="pending"
    )
    error_message: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)

    file_size_bytes: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)

    expires_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)

    # Relationships
    scheduled_export: Mapped[Optional["ScheduledExport"]] = relationship(back_populates="history")
