export default {
  // example structure for handling api endpoints based on business entities
  // please keep these in alphabetical order and group them if they extend off the same initial url
  // examples: '/examples',
  // examplesNumbers: '/examples/numbers',
  //
  // can be called with the api filter like so
  // this.$api.get(inventoryService.examples, { id: entryId })
  accessionJobs: '/accession-jobs/',
  accessionJobsWorkflow: '/accession-jobs/workflow/',
  aisles: '/aisles/',
  aislesNumbers: '/aisles/numbers',
  authLegacyLogin: '/auth/legacy/login',
  authSsoLogin: '/auth/sso/login/',
  authSsoLogout: '/auth/sso/logout/',
  barcodes: '/barcodes/',
  barcodesValue: '/barcodes/value/',
  batchUpload: '/batch-upload/',
  batchUploadLocationManagement: '/batch-upload/location-management',
  buildings: '/buildings/',
  containerTypes: '/container-types/',
  groups: '/groups/',
  history: '/history/',
  items: '/items/',
  itemsBarcode: '/items/barcode/',
  itemsMove: '/items/move/',
  mediaTypes: '/media-types/',
  modules: '/modules/',
  nonTrayItems: '/non_tray_items/',
  nonTrayItemsBarcode: '/non_tray_items/barcode/',
  nonTrayItemsMove: '/non_tray_items/move/',
  ladders: '/ladders/',
  owners: '/owners/',
  ownersTiers: '/owners/tiers',
  permissions: '/permissions/',
  picklists: '/pick-lists/',
  refileJobs: '/refile-jobs/',
  refileQueue: '/refile-queue/',
  reportingAccessionItems: '/reporting/accession-items/',
  reportingOpenLocations: '/reporting/open-locations/',
  reportingShelvingDiscrepancies: '/reporting/shelving-job-discrepancies/',
  reportingMoveDiscrepancies: '/reporting/move-discrepancies/',
  reportingTrayItemsCount: '/reporting/tray_items/count/',
  reportingAislesItemsCount: '/reporting/aisles/items_count/',
  reportingNonTrayItemsCount: '/reporting/non_tray_items/count/',
  reportingRetrievalsCount: '/reporting/retrievals/count/',
  reportingUserJobsCount: '/reporting/user-jobs/count/',
  reportingVerificationChangesSummary: '/reporting/verification-changes/summary/',
  requests: '/requests/',
  requestsLocations: '/requests/locations',
  requestsPriorities: '/requests/priorities',
  requestsTypes: '/requests/types',
  shelfTypes: '/shelf-types/',
  shelves: '/shelves/',
  shelvesBarcode: '/shelves/barcode/',
  shelvesPositions: '/shelves/positions/',
  shelvingJobs: '/shelving-jobs/',
  sides: '/sides/',
  sizeClass: '/size_class/',
  trays: '/trays/',
  traysBarcode: '/trays/barcode/',
  traysMove: '/trays/move/',
  users: '/users/',
  verificationJobs: '/verification-jobs/',
  verificationJobsDropdown: '/verification-jobs/dropdown/',
  verificationJobsByAccessionJobId: '/verification-jobs/by-accession-job-id/',
  verificationJobsWorkflow: '/verification-jobs/workflow/',
  withdrawJobs: '/withdraw-jobs/'
}
